#!/bin/sh

installed=0

if [ -z "$B43_ASM" ]; then
	if [ $installed -eq 0 ] && [ -x "./b43-asm.bin" ]; then
		B43_ASM="./b43-asm.bin"
	else
		B43_ASM="b43-asm.bin"
	fi
fi

if [ -z "$CPP" ]; then
	CPP="cpp"
fi

if [ $# -lt 2 ]; then
	$B43_ASM --help
	exit 1
fi

infile="$1"
shift
outfile="$1"
shift

cat "$infile" | $CPP -traditional-cpp | $B43_ASM "-" "$outfile" $@
