#!/bin/sh

set -e

if [ "$1" = purge ] || [ "$1" = remove ]; then

        if [ -d /lib/firmware/b43legacy ]; then
                echo "Deleting old extracted firmware..."
                rm -rf /lib/firmware/b43legacy/*
        fi
fi



exit 0 
