#!/bin/sh

installed=0

if [ $# -ne 2 ]; then
	echo "Usage: $0 input_file.fw output_file.asm"
	exit 1
fi

if [ -z "$B43_DASM" ]; then
	if [ $installed -eq 0 ] && [ -x "./b43-dasm.bin" ]; then
		B43_DASM="./b43-dasm.bin"
	else
		B43_DASM="b43-dasm.bin"
	fi
fi

infile="$1"
outfile="$2"

cat "$infile" | $B43_DASM "$outfile"

